[package]
name = "topos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.1"
bytemuck = { version = "1.13.1", features = [ "derive" ] }
cosmic-text = "0.8.0"
env_logger = "0.10.0"
etagere = "0.2.7"
euclid = "0.22.9"
futures = "0.3.28"
itertools = "0.10.5"
log = "0.4.18"
num-traits = "0.2.15"
palette = "0.7.2"
pollster = "0.3.0"
pretty_env_logger = "0.5.0"
rayon = "1.7.0"
rustc-hash = "1.1.0"
swash = "0.1.8"
tao = "0.20.0"
wgpu = "0.16.0"
winit = "0.28.6"
